### ISSUE TITLE
K8s: Turn on all tests in all related projects

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#1024]
Check and ensure that the unit and integration tests for the occurrence and pipelines projects are working

**Comment by marcos-lg** [comment]
I enabled the jenkins job of occurrence and added the missing modules and seems to work. I also deleted the occurrence-hive-udf module. The occurrence-trino-udf hasn't been added to the occurrence-motherpom because it uses java 17. I created a different job in jenkins to build it.

In pipelines I just removed the clustering-oozie module and tests seem to work.
