### ISSUE TITLE
Investigate how an full core file can be exported to Avro

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#13]
Create an Avro schema with all DwC, DC and Gbif terms: http://rs.tdwg.org/dwc/terms/ 
http://purl.org/dc/terms/

**Comment by timrobertson100** [comment]
It might have been discussed, but I propose consider if you need to do this.  

The intention in [the readme](https://github.com/gbif/pipelines/blob/master/README.md) was to keep verbatim data in a star schema form which is modelled [in this avro schema](https://github.com/gbif/pipelines/blob/master/core/src/main/avro/dwca.avsc).  

As categories of data are interpreted schemas be created for the interpreted data, so you end up with e.g.:

 1. `verbatim.avro` holding the raw data
 2. `temporal.avro` holding the interpreted date/time information
 3. `gbif-taxonomy.avro` holding the interpreted taxonomy according to the GBIF backbone

It does mean that to access data from the verbatim data you would need a function like `getString(Term field)` (e.g. `getString(DwC.scientificName`) rather than `getScientificName()` but I believe this will prove better as more and more data are added since the verbatim schema remains unchanged.

This design should allow intuitive extensibility (e.g. adding things like interpretation for protected areas, sites of scientific interest etc)  and only storing information that are interpreted into the new files.

**Comment by fmendezh** [comment]
@timrobertson100 for your surprise @aalbatross had the same idea: a generic dwca Avro schema and specific Avro schemas for each group of transformations/interpretations
