### ISSUE TITLE
Geo lookup performance problem

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#145]
Right now the geo lookup interpretation step is the slowest one, can take 90% of all interpretation time.

We need to fix that, maybe instead of calling the geo lookup service, move map cache to client-side or something similar (use as an external library)

Please look at:
https://github.com/gbif/geocode/blob/master/geocode-ws/MapImageLookup.md

**Comment by timrobertson100** [comment]
We are going to need to intersect many polygons with the occurrence data (protected areas, habitats etc) very soon (Feb/March). Because of there are not that many distinct coordinates in GBIF mediated data (40m or so?), I’d suggest we consider an HBase backed cache. The cache client would be applied at both server (i.e. behind a geocode webservice) but could also be used within the Beam pipeline. Once warm HBase will serve 100,000s / sec on our cluster if designed correctly (i.e. no hotspotting of keys by e.g. hash based salting keys).


Tim

**Comment by MattBlissett** [comment]
The number from January's analytics is 69,306,445.
