### ISSUE TITLE
Handle registry change events

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#162]
When a dataset is changed in the registry (e.g. moving organization) this is broadcast on the registry change queue. All records for the dataset need to be reinterpreted to pick up the changed values.

**Comment by asturcon** [comment]
Modified pipelines to handle the registry changes.

PENDING: if there is a change in a dataset but the crawling for this dataset is stopped because it wasn't modified we need to update that in our avro files and ES (now in PROD it uses a MR job to update Hbase).

IMPROVEMENT: when a previously deleted dataset is restored, if the crawling for this dataset is stopped because it wasn't modified the avro files and ES are not being updated (it happens the same in PROD now).

**Comment by asturcon** [comment]
done covering the functionality that we have now in production
