### ISSUE TITLE
Integrate Vocabulary Service into Pipelines

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#216]
The project (Vocabulary)[https://github.com/gbif/vocabulary] implements a simple service with the CRUD and lookup services for accessing and managing vocabularies based on known terms used during data ingestion. Pipelines need to access managed concepts and terms to eliminate dependencies on libraries (parsers) implemented on top of file-based-static dictionaries.  
The lookup mechanism should cope with the performance requirements of pipelines to avoid a major regression in terms of interpretation/indexing time. This may require some sort of caching mechanism to load term lookups on-demand or else pre-load them at the moment of starting a pipeline job.

**Comment by timrobertson100** [comment]
I'd recommend ensuring that an entire vocabulary can be downloaded in a single HTTP call (e.g. on JVM startup) and use that as the basis for the interpretation. I suggest any client that enables that be developed as a small module in the vocab service too for other tools to use in the future (e.g. an IPT)

**Comment by asturcon** [comment]
What I see there is that if we do that it should be downloaded in a key-value format or something easy to work with and that won't change over time, because if you download the vocabulary as it is the client should know how to look up a term there like checking all the different languages, the alternative labels, the misspelt labels (also this internal representation may change, therefore the lookup may change too).

**Comment by timrobertson100** [comment]
Good points. I imagined e.g. a `/vocabulary/123/export.json` API or similar and then a small library that provided that functionality in-memory. I suggested keeping it in the vocabulary project so that it could then evolve over time through versioning and change.

A user of this (the pipelines being the first) would then be able to do something along the lines of:

```
@Threadsafe
Vocabulary basisOfRecord = Vocabularies.load(GBIF_BASE_API, "dwc:basisOfRecord");

Optional<Concept> c1 = basisOfRecord.lookup("preservadoio");
Optional<Concept> c2 = basisOfRecord.lookup("preservadoio", Language.es);
```

Or something along those lines. This would need an in-memory index and we should be very careful to choose something with light dependencies to be widely reusable (possible vendoring it to avoid classpath issues for userS)

**Comment by tucotuco** [comment]
Hi folks. Are the vocabularies yet open for change? @pzermoglio will
certainly want to say something about the state of vocabs in the pioeline
in her TDWG BDQ Task Group 4 (Best practices for vocabularies of values)
meeting.

**Comment by timrobertson100** [comment]
They are not, nor actually implemented in the pipelines yet.

This first stage is to get this out of codebases (i.e. Java Jar files) and into a DB (what this issue relates to). Next will be a UI (to come in 2-3 months) followed by a series of cleanup activities using the existing data observed in occurrences as the basis for that.

**Comment by muttcg** [comment]
in prod
