### ISSUE TITLE
ALA Q4 - Extensible RecordTypes

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#279]
Extensible RecordTypes - we have created ALARecordTypes

**Comment by muttcg** [comment]
@djtfmartin as I understand it is about the way how to add things in models, right?

**Comment by djtfmartin** [comment]
Thanks @muttcg. This was just a reference to this class:

https://github.com/AtlasOfLivingAustralia/la-pipelines/blob/master/pipelines/src/main/java/au/org/ala/pipelines/common/ALARecordTypes.java

I dont think its a problem as such if we aim to work from the same codebase instead of taking the gbif pipelines as a library approach we where taking with la-pipelines.

**Comment by muttcg** [comment]
Close all ALA Q*
