### ISSUE TITLE
ALA Q5 - Rename AustralianSpatialRecord

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#280]
Rename AustralianSpatialRecord to something more generic...

**Comment by muttcg** [comment]
@djtfmartin Any suggestions?

**Comment by djtfmartin** [comment]
thanks @muttcg. 

I'll suggest `SamplingRecord` but i'm not wedded to that idea. Whenever i refer to "sampling" outside of the ALA, it usually confuses people so i'm open to ideas. The main thing is that there isn't anything Australian specific about this activity or information.

@timrobertson100 any ideas ?

**Comment by timrobertson100** [comment]
_Sampling_ as a name isn't so intuitive as it generally assumed to mean a sub-sample (e.g. random N sampled), a momentary value from a continuous wave (e.g. a temperature at a time) or the result of a physical collection (e.g. soil sample for DNA analysis).

Given this object is just capturing key-value pairs and tracking issues, I'd have initially suggested `DynamicProperties`. However, that is also problematic since it is also used as a name in a field in Darwin Core.

Given it is intended to capture information for a location how about `LocationFeatures` as _feature_ is commonly used in spatial services?

**Comment by djtfmartin** [comment]
Sounds good to me. I'd be tempted to remove the `issues` property as we are not using them. I'd rather add them once we are.

**Comment by MattBlissett** [comment]
I don't know what AustralianSpatialRecord does, but does "feature" fit with the definition in _Georeferencing Best Practices_?

> an object of observation, measurement, or reference that can be represented spatially. Often categorized into "feature types" (e.g., mountain, road, populated place, etc.) and given names for specific instances (e.g., "Mount Everest", "Ruta 40", "Istanbul"), which are also sometimes referred to as "named places", "place names" or "toponyms".

**Comment by timrobertson100** [comment]
> but does "feature" fit with the definition in Georeferencing Best Practices?

No, and it doesn't fit exactly with the GML [definition of Feature](https://en.wikipedia.org/wiki/Geography_Markup_Language#Features) either.

However, since feature is really [defined](https://www.lexico.com/definition/feature) as _a distinctive attribute or aspect of something_ and these are records capturing attributes/aspects of a location I felt LocationFeature seemed reasonable. Happy to see alternative suggestions though.
