### ISSUE TITLE
Index dwc:GeologicalContext terms

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#400]
A request by email from representatives of si.edu, fsu.edu, and colorado.edu, supported by the  TDWG Earth Sciences and Paleobiology Interest Group:

> [We] co-facilitate a paleo data working group mostly composed of people working with paleo collections and creating records that are published to aggregators. One point of discussion for the group has been the accessibility and discoverability of paleo data within aggregators like GBIF. A vital data point for fossil occurrences is found in the Darwin Core Geological Context terms, but these terms are not searchable in the current GBIF portal interface. We are inquiring about what the current situation is for indexing of these terms and the possibilities of indexing some or all of these terms if they aren’t already? and if they can be made searchable within the search interface? We note that the availability of geologic context terms in the iDigBio Portal, both via their search interface and their API directly, has greatly increased the use of iDigBio by paleo collections in the United States. This inquiry is also supported by the TDWG Earth Sciences and Paleobiology Interest Group.

The terms being requested for search are all in the DwC namespace:

- earliestEonOrLowestEonothem
- latestEonOrHighestEonothem
- earliestEraOrLowestErathem
- latestEraOrHighestErathem
- earliestPeriodOrLowestSystem
- latestPeriodOrHighestSystem
- earliestEpochOrLowestSeries
- latestEpochOrHighestSeries
- earliestAgeOrLowestStage
- latestAgeOrHighestStage
- lowestBiostratigraphicZone
- highestBiostratigraphicZone
- group
- formation
- member
- bed

**Comment by ekrimmel** [comment]
The new ability to query GBIF occurrence records based on the presence of DWCA extension data is really awesome! I'm curious if this issue is on a development timeline yet?

**Comment by muttcg** [comment]
Hi @ekrimmel
We haven't planned to take it to work yet.

**Comment by ljwalker** [comment]
I strongly agree that the Darwin Core Geological Context terms should be indexed and added to the GBIF portal's search interface. Simply put, without them, paleontological datasets on GBIF are limited in use, which is disappointing (and frustrating) given the significant resources the paleo community puts toward digitizing its lithostratigraphic data. For this reason, I often direct researchers to iDigBio because their portal does accommodate these terms.

**Comment by MortenHofft** [comment]
In an attempt to make it easier to get this request implemented it might be nice to clarify what if any processing is expected
The fields in the standard does not have a vocabulary as far as I know
https://dwc.tdwg.org/list/#dwc_earliestEonOrLowestEonothem

Would this just be text exactly as provided by the publisher or would it have to be normalised and aligned with a vocabulary (I imagine the latter). Is there an existing vocabulary or should one be created?

**Comment by ekrimmel** [comment]
So exciting to see continued attention being put towards this, @MortenHofft – thank you! Processing the values in these fields would be very helpful for discoverability.

There are two main categories of terms in the DwC Geological Context class: those referring to chronostratigraphy (time) and those referring to lithostratigraphy (rock). You are correct that neither has an official vocabulary to reference for processing, however, there are resources for each that could be the basis of a community vocabulary maintained on GBIF.

A vocabulary for chronostratigraphy is relatively straightforward. The International Commission on Stratigraphy publishes a [chronostratigraphic chart](https://stratigraphy.org/chart) (unfortunately not in a very digitally accessible format) that includes official values you would expect to find for chronostratigraphy. There are also regional variations for chronostratigraphic values, but accommodating those could be part of a second layer of complexity for vocabulary development. The following DwC terms describe chronostratigraphy: 
- _earliestEonOrLowestEonothem_
- _latestEonOrHighestEonothem_
- _earliestEraOrLowestErathem_
- _latestEraOrHighestErathem_
- _earliestPeriodOrLowestSystem_
- _latestPeriodOrHighestSystem_
- _earliestEpochOrLowestSeries_
- _latestEpochOrHighestSeries_
- _earliestAgeOrLowestStage_
- _latestAgeOrHighestStage_

Lithostratigraphy is more complex. [Macrostrat](https://macrostrat.org/) makes a lot of values for North American stratigraphic units available via GUI and an API. Unsure if there are complementary regional equivalents, or a globally scoped source. You could expect to find values for the following DwC terms on Macrostrat:
- _group_, e.g "[Admire Gp](https://macrostrat.org/sift/#/strat_name/2358)"
- _formation_, e.g. "[Green River Fm](https://macrostrat.org/sift/#/strat_name/795)"
- _member_, e.g. "[Douglas Creek Mbr](https://macrostrat.org/sift/#/strat_name/7001)"
- _bed_, e.g "[Kimball Mountain Bed](https://macrostrat.org/sift/#/strat_name/71610)"

The final two terms in the DwC Geological Context class are _lowestBiostratigraphicZone_ and _highestBiostratigraphicZone_, and I do not think there is not a good source of globally-scoped values to use in a vocabulary for these fields. Processing for these fields is also lower priority for us.

We recognize that the data coming from providers in these fields is not as uniform as it could be (@tucotuco acquired [unique value lists](https://github.com/tdwg/dwc-qa/tree/master/data/GBIFDistinctValues/2022-03-08) for us last year so that we could see just how "not uniform"). But even as data providers recognize this and agree to better regulate ourselves, we'll never be able to provide data as uniform as GBIF processing can make it. Members of our [Paleo Data Working Group](https://paleo-data.github.io/) would be excited to put time into creating and maintaining controlled vocabularies for the GeologicalContext terms if it means GBIF will begin indexing them, so please let us know how we can help!

**Comment by MortenHofft** [comment]
Thank you for a thorough answer and volunteering to help! Does below make sense?

Sounds like we could start with a vocabulary for chronostratigraphy, and then just have raw values for lithostratigraphy and BiostratigraphicZone? If global resources for the latter two is discovered we could revisit.

**Chronostratigraphy**
For chronostratigraphy the page you link to links to this [interactive resource](https://stratigraphy.org/timescale/) that links to a [github repo with json](https://github.com/CSIRO-enviro-informatics/interactive-geological-timescale/blob/master/src/assets/timeline_data.json) that links to a a [vocabulary hosted by csiro](https://vocabs.ardc.edu.au/repository/api/lda/csiro/international-chronostratigraphic-chart/geologic-time-scale-2020/resource?uri=http://resource.geosciml.org/classifier/ics/ischart/Precambrian). 
At first glance it looks easy to generate a GBIF vocabulary based on e.g. the JSON.

**Comment by ekrimmel** [comment]
What you propose above sounds like a terrific start!

**Comment by CecSve** [comment]
> **Chronostratigraphy**
> For chronostratigraphy the page you link to links to this [interactive resource](https://stratigraphy.org/timescale/) that links to a [github repo with json](https://github.com/CSIRO-enviro-informatics/interactive-geological-timescale/blob/master/src/assets/timeline_data.json) that links to a a [vocabulary hosted by csiro](https://vocabs.ardc.edu.au/repository/api/lda/csiro/international-chronostratigraphic-chart/geologic-time-scale-2020/resource?uri=http://resource.geosciml.org/classifier/ics/ischart/Precambrian).
> At first glance it looks easy to generate a GBIF vocabulary based on e.g. the JSON.
> Ideally inconsistent values would get a quality issue flag (e.g. `Era: Mesoproterozoic; System: Orosirian` is wrong I assume, as `Orosirian` is sitting under the `Paleoproterozoic` Era)

@timrobertson100 (anyone I should tag instead?) would it make sense to import to the vocabulary server straight away so any further editing could happen within the tool? The vocabulary has nested concepts.

**Comment by CecSve** [comment]
@ekrimmel and the rest of the Paleo Data Working Group - I have created an issue and a work sheet for a Chronostratigraphy vocabulary: https://github.com/gbif/vocabulary/issues/121. The first step would be to map the verbatim values from the unique values list that was created to the concepts, and it would be great if people from the work group could do this! If you want to get started, I propose we have a short call where I present the layout of the sheet, the parent/child relationship between the concepts and how to we usually deal with mapping the verbatim values. 

Please contact helpdesk@gbif.org if you want to set up a meeting.

**Comment by ekrimmel** [comment]
Thank you, @CecSve! I'll coordinate within our group and see who is available to help, then reach out via the help desk email to set up a meeting.

**Comment by muttcg** [comment]
Deployed to PROD

**Comment by CecSve** [comment]
Thanks @muttcg! Now occurrence pages contain the information of the terms within geologicalContext (for example https://www.gbif.org/occurrence/4142185317) and the terms are searchable in the API https://api.gbif.org/v1/occurrence/search?earliestPeriodOrLowestSystem=Paleogene @ekrimmel
