### ISSUE TITLE
Idea for new data quality flag COORDINATES_MATCH_ADMIN_CENTROID

### ISSUE THREAD

**Issue by tucotuco** [gbif/pipelines#454]
There are lots of things to consider for a flag like this. First is that there are a lot of different "centroids" (four common ones, for example, are geographic center, center of gravity, and center of minimum bounding circle). Second is the effect of the precision of the geometries used to determine them, both from the source that produced the coordinates and from the side testing for coincidence. A reasonable buffer size needs to accommodate both. Third is which administrative levels to check against. The more specific the level, the more likely the coordinates really do apply because the location has not more specific information. 

If this feature is considered, it would be good to see if the various "centers" could be pre-calculated and made accessible via the geocode API.

**Comment by MattBlissett** [comment]
http://api.gbif.org/v1/geocode/reverse?lat=54&lng=-2 is an example of a centroid from CoordinateCleaner and GeoLocate.

The centroids in that service are from the two SQL files in https://github.com/gbif/geocode/tree/master/database

I added this, but stopped before implementing it in pipelines since I was concerned about the issues you raise.  The first centroid I checked -- that one, 54°N 2°W for Great Britain (or maybe the UK) -- has thousands of nearby, genuine occurrences: https://www.gbif.org/occurrence/map?geometry=POLYGON((-2.1%2053.9,-1.9%2053.9,-1.9%2054.1,-2.1%2054.1,-2.1%2053.9))

**Comment by MattBlissett** [comment]
The discussion for this is under https://github.com/gbif/portal-feedback/issues/4232
