### ISSUE TITLE
Data validator

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#542]
TODO: Description

**Comment by jhnwllr** [comment]
Here is my current thinking and wishes for the new data validator: 

**Backend** prioritized wishlist:
1. Output **downloadable report** of issues found.
2. Any size archives would be nice (not just 100 mb).
3. Somehow runnable locally as well as on GBIF would be a bonus.

**UI** prioritized wishlist:
1. Previous validations available on user pages.
2. Should give users issues by order of importance.
3. **What**, **Where**, **When** flags given priority.

**What** (taxonomic information)
**Where** (coordinate issues)
**When** (date issues)

Additional issue flags :

1. Centroid flagging (medium)
2. Gridded dataset flag (medium)
3. Any zero coordinate flagging (easy)  
4. Default coordinate uncertainty in meters (easy)
5. is_cluster flag (?) 
6. is_outlier flag (hard)

I assume these additional issues could be handled separately, since validator will mirror pipelines processing. So we just need to add a feature to pipelines and it will be in the data validator...

**Comment by jlegind** [comment]
Hi, I would like a feature where clustering behavior is reported. This is to help publishers avoid duplication or submitting records already in GBIF from other publishing organizations. It should at least give them an opportunity to see if clustering behavior is uncovering duplicates.

**Comment by timrobertson100** [comment]
> I would like a feature where clustering behavior is reported. This is to help publishers avoid duplication or submitting records already in GBIF from other publishing organizations.

This is understandable, but I'm afraid is not something we will be able to easily achieve. Currently, and for the foreseeable future, clustering runs as a batch process across all data.
