### ISSUE TITLE
Change cluster.routing.allocation.disk.watermark.high for IT

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#568]
ITs get fail when disk space is below 90%, which is redundant for IT and breaks Jenkins build all the time

**Comment by MattBlissett** [comment]
There is plenty more space available for the VM, if we need it.  Would that make all this a lot simpler?

(We have had a recent unexpected increase in disk use with the training courses, since they added several gigabytes of video as part of their builds.  pipelines-dev, pipelines-542, pipelines-master and pipelines are all about 4GB on disk in Jenkins.)

**Comment by MattBlissett** [comment]
There's now about 160GB free on Jenkins.

**Comment by muttcg** [comment]
@MattBlissett Thanks, I also disabled the disk allocation threshold for ES ITs
