### ISSUE TITLE
Cannot ingest some datasets because column separator detection is going wrong

### ISSUE THREAD

**Issue by sylvain-morin** [gbif/pipelines#602]
This issue is linked to https://github.com/gbif/dwca-io/issues/57

As a consequence, the dwca-avro step is producing a wrong verbatim.avro file (the step is successful).

However, the following step (interpret) is failing because of the wrong verbatim content:
```
{
    "id" : "RECORD_ID_ERROR",
    "coreRowType" : "http://rs.tdwg.org/dwc/terms/Occurrence",
    "coreTerms" : {},
    "extensions" : {}
} 
```

**Comment by sylmorin-gbif** [comment]
Attaching the dataset:
[dwca.zip](https://github.com/gbif/pipelines/files/7309535/dwca.zip)

**Comment by muttcg** [comment]
Hi!
I don't think that patching the codebase is the right way. We can't add ';' as a default separator, because we have many archives using ';' inside text fields and etc and also use '|' as a separator for multi-value fields like authors/identiedBy/etc.

Please try @mdoering 's  suggestion https://github.com/gbif/dwca-io/issues/57#issuecomment-938536756

Sounds like for that case with multiple locations you may need to use https://dwc.tdwg.org/terms/#event type and occurrence as an extension

**Comment by muttcg** [comment]
Example of meta.xml:

```
<archive xmlns="http://rs.tdwg.org/dwc/text/" metadata="eml.xml">
  <core encoding="UTF-8" linesTerminatedBy="\r\n" fieldsTerminatedBy="\t" fieldsEnclosedBy=""" ignoreHeaderLines="0" rowType="http://rs.tdwg.org/dwc/terms/Occurrence">
  <files>
  <location>occurrence.tsv</location>
  </files>
  <id index="0"/>
  <field index="0" term="http://rs.tdwg.org/dwc/terms/occurrenceID"/>
  </core>
</archive>
```
You need to change **fieldsTerminatedBy="\t"** -> **fieldsTerminatedBy=";"**

**Comment by sylmorin-gbif** [comment]
Hello,

I confirm that adding the meta.xml file allows us to configure the column separator.
The dataset is now correctly ingested by the ALA pipeline.

The only "drawback" of adding the meta.xml file, is that we have to express the whole mapping of columns inside meta.xml file - it's no more automatically "detected"

**Comment by muttcg** [comment]
Thanks,

Unfortunately, it is a tradeoff, you configure via data layer or change the codebase and configure via ingestion layer

You are welcome to create issues here in case of issues with ingestion
