### ISSUE TITLE
Improve stability of record identifiers

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#677]
There are growing initiatives that aim to annotate or assert links to GBIF-mediated data. Two examples include [Bionomia](https://bionomia.net) which aims to disambiguate person names, linking collectors to their records and  [Plazi](https://plazi.org/) which identifies citations of specimens in literature. These initiatives are affected when GBIF IDs change, as links go stale, and effort spent determining links can be lost.  Ultimately, the opportunity to provide enrichments and citations of data to the original data owners suffers as a result.

This _umbrella_ issue tracks tasks that should help raise the visibility of the importance of id stability, and 
improve processes to allow migrations and detection of unwitting changes.

### Background
Records come in to GBIF.org packaged as datasets. The system inspects the `occurrenceID` and the combination of the `institutionCode`, `collectionCode`  and  `catalogNumber`, known as the _triplet_, and compares these to a lookup table to determine if either have been seen before for the dataset. This determines if an update should be applied, or if a new record is seen and ID issued.

- _Triplets_ regularly change, but the `occurrenceID` is often enough to maintain stability
- Datasets being repackaged (e.g. lumping datasets into a single dataset) is a common reason for IDs to change
- Changes in formatting of `occurrenceID` for technical reasons such as `http` to `https` or a new IT system deployment e.g. `acme.com/mysystem.php?id=123` to `acme.com/cms/H/123` are common
- There are cases when `triplets` and `occurrenceIDs` are misused in combinations, and results in some [unusual diagnostics](https://github.com/gbif/pipelines/issues?q=is%3Aissue+diagnostic+id)

GBIF very [recently deployed](https://www.gbif.org/release-notes#29jan22) a change that halts data ingestion if >5% of record IDs are seen to change, with notification to data managers.

### Improvements

- [x] #676 
- [x] #675  
- [x] #673 

NOTE:  #674 detached from the epic

**Comment by dagendresen** [comment]
Maybe some combination of terms like `recordedByID` + `recordNumber` + `eventDate` + `location` might be more appropriate for maintaining the stability of `occurrenceID`s -- than the DwC triplet??

**Comment by dagendresen** [comment]
Agree not necessarily more stable - but more **appropriate**. Arguably, no `Occurrence`s are ever correctly assigned neither `institutionCode` nor `collectionCode` nor `catalogNumber` (sensu DwC term definitions)

**Comment by timrobertson100** [comment]
Just to link resources, a related discussion on WikiData is [underway](https://www.wikidata.org/wiki/Wikidata:Property_proposal/GBIF_occurrence_ID)

**Comment by rondlg** [comment]
At the risk of getting into the weeds, another part of the problem is the round trip of all these identifiers back to the home institution. As an example:

1) Museum assigns a GUID an an identifier then they publish their record "x-y-z"
2) Aggregator 1 picks up that record and assigns it own identifier "1-a-b"
3) Aggregator 2 picks up the record and also assigns its own identifier "6-y-o"
4) Researcher A pulls data from Aggregator 2 and writes a paper using "6-y-o"
5) Researcher B pulls data from Aggregator 1 and writes a paper using "1-a-b"

How does the Museum get the identifiers "1-a-b" and "6-y-o" back so that when it tries to update its record with the new information from Researcher A and Researcher B it can connect the pieces? Otherwise the risk/situation could/does occur that the next time it publishes you get 3 records!

**Comment by dshorthouse** [comment]
@rondlg Strikes me that **someone** ought to have well-worn and robust resolution/reconciliation/translation services & that whosoever has an identifier of any flavour in-hand can use this to deduce whatsoever alternate identifier that suits their purpose. The danger comes with overly generous depictions of `sameAs` relationships if the underlying entities are *not* in fact, `sameAs` as described by @dagendresen (i.e. material that participated directly in a collecting event, derivative material without a direct collecting event, occurrence as an envelope of material & a collecting event, or some other topological space that, though truer to reality, frustrates users if clarity is in short supply).

**Comment by deepreef** [comment]
@dshorthouse:
> Strikes me that someone ought to serve well-worn and robust resolution/reconciliation/translation services & that whosoever has an identifier of any flavour in-hand can use this to deduce whatsoever alternate identifier that suits their purpose.

What you allude to is what the original *intention* of [BioGUID](http://bioguid.org) was to be.  One of the reasons progress on that stalled boils down to:

> The danger comes with overly generous depictions of `sameAs` relationships if the underlying entities are not in fact, `sameAs `

Indeed, there be dragons on that slippery slope (to conflate metaphors).  The original seed content of BioGUID (~1 billion records, mostly from GBIF) is flawed, because it presumed that an identifier for an `Occurrence` represented the "sameAs" identifier for a "Specimen".  Even back then I knew that was not going to work, so I expanded the data model to accommodate non-`sameAs` associations between identifiers that represented (slightly) different things (sometimes slightly different classes of things).  Unfortunately, I never got beyond "relatedTo" as an additional alternative to `sameAs`, and finally decided not to throw any more time at developing BioGUID until "**someone**" sorted out a controlled vocabulary with robust definitions of relationship types that our TDWG-y community could adopt.

So, while BioGUID never lived up to its intentions (i.e., it never achieved "well-worn" or "robust" status), a lot of thought went into how you would model the relationships between identifiers.  While the model could use some tweaking, I think it's essentially "there" in terms of what such resolution/reconciliation/translation services would need in order to achieve well-worn/robust status (see [here](http://bioguid.org/about)).

I would **LOVE** for GBIF to take on that task, and would be more than happy to contribute whatever I can to help.

**Comment by muttcg** [comment]
The current version has been deployed to production, we will monitor the stability for some time to understand what changes and results we want to achieve, and improve the process by creating new "feature" issues.

**Comment by dshorthouse** [comment]
fwiw, here's a recent example where the `occurrenceID` was changed for the entire? dataset for what seems like administrative reasons. 
"old" occurrence record: https://www.gbif.org/occurrence/3424591260
new occurrence record: https://www.gbif.org/occurrence/1086615857
All the `gbifID` values have changed because the (computed?) `occurrenceID` values changed from an example like BRA:UPCB:UPCB:10001 to BRA:UFPR:UPCB:10001

**Comment by timrobertson100** [comment]
Thanks for reporting this @dshorthouse - it all helps in maturing these processes. I looked at how this dataset has evolved over a few snapshots.

1. In Jan 2021 `BRA:U**FPR**:UPCB:*` format was used 
2. By September 2022 `BRA:U**PCB**:UPCB` was used
3. At some point since 1st Oct 2022 they reverted to `BRA:U**FPR**:UPCB:*` 

_(I can find more exact times but that won't really shed any more light)_

Our ID change detection, as implemented halts the process when we detect that >N% of the dataset (configurable) will result in new IDs being issued. In this scenario, it was in fact resurrecting old IDs so passed this condition.

I suggest we don't do anything here, and you make the migration of IDs on your side. Seem reasonable? 
Do you think we should modify the behavior to also detect these reversion cases?

On a more optimistic note, the new procedures would have halted the original change for confirmation, so this will be less likely to happen in the future.

**Comment by dshorthouse** [comment]
> I suggest we don't do anything here, and you make the migration of IDs on your side. Seem reasonable?
> Do you think we should modify the behavior to also detect these reversion cases?

I figured there was some flip-flopping because the affected gbifIDs post October 1 were smaller than before, which to me – with slight insider knowledge – indicated a reversion to an earlier state. I'm not sure that there is a technical solution here other than to use it as an example toward implementing HTTP 301 redirects.

I suspect you'll get mixed responses from users if asked whether or not gbifIDs should be resurrected because in practice it depends very much on the synchrony a user wishes to support & in what environment their processes are at play. A two-week gap in synchrony for Bionomia to gather records from GBIF seemed acceptable, but is rather arbitrary. A more real-time call to GBIF APIs might be more appropriate for other projects. In that case, such flip-flopping is undesirable if it means that at any point, a 404 might be thrown when a 301 would have been more seamless (eg https://api.gbif.org/v1/occurrence/3424591260 gives a 404 whereas https://gbif.org/occurrence/3424591260 gives a 200 with a fragment).
