### ISSUE TITLE
OccurrenceIDs to be regenerated for Norwegian dataset - Inner Oslofjorden Phytoplankton Database

### ISSUE THREAD

**Issue by rukayaj** [gbif/pipelines#696]
We've unfortunately run into a problem with a dataset where the data has unexpectedly changed so dramatically that we are unable to keep mapping the UUIDs we generated for publishing. More info here https://github.com/gbif-norway/helpdesk/issues/17#issuecomment-1080598066. 

I know that occurrenceID and eventID stability is something GBIF is thinking about (https://github.com/gbif/pipelines/issues/677). So we were wondering, is there anything special we should do for this dataset, or can we just regenerate the UUIDs and go ahead and publish? 

Quick links:
GBIF: https://www.gbif.org/dataset/777ea835-48a3-4136-bf3a-32c5b897563f
IPT: https://ipt.gbif.no/resource?r=oslofjord_phytoplankton
Bionomia: https://bionomia.net/dataset/777ea835-48a3-4136-bf3a-32c5b897563f (no links)

**Comment by timrobertson100** [comment]
Thanks for asking @rukayaj 

The only group that notices and raises this regularly is the Bionomia group. For GBIF operations and most consumers, it is not an issue. 

We will provide tools to allow ID migration in the not-to-distant future, but in this instance, since there are no Bionomia links I suggest just republishing the data with new UUIDs.

**Comment by rukayaj** [comment]
Great, just checking. Thanks!
