### ISSUE TITLE
Raw event date supplied but is not processed

### ISSUE THREAD

**Issue by patkyn** [gbif/pipelines#753]
https://atlaslivingaustralia.slack.com/archives/CCURT5KAA/p1655698038540639

There are currently 101,426,741 records that have raw_eventDate supplied.
https://biocache.ala.org.au/occurrences/search?q=country%3AAustralia&fq=raw_eventDate%3A*
![image](https://user-images.githubusercontent.com/1606595/176328739-039f11ec-b78a-43fd-94d4-0c1d76977e86.png)

Despite being supplied with valid iso format of raw event date, 45,580,159 records still to appear as without processed eventDate.
https://biocache.ala.org.au/occurrences/search?q=country%3AAustralia&fq=raw_eventDate%3A*&fq=-eventDate%3A*
![image](https://user-images.githubusercontent.com/1606595/176329076-8c488da9-ba37-4c47-ba5e-e7cefabe2290.png)
For eg: https://biocache.ala.org.au/occurrences/9c541ca4-af29-4b00-9106-a01a1840a1fd
![image](https://user-images.githubusercontent.com/1606595/176329285-8eb40adf-fa04-4189-a92d-ff3f2aa4e6cd.png)

**Comment by peggynewman** [comment]
Seems to be down to 8m now in biocache-databox, so that's much better. https://biocache-databox.ala.org.au/occurrences/search?q=country%3AAustralia&fq=raw_eventDate%3A*&fq=-eventDate%3A*&qualityProfile=ALA&disableAllQualityFilters=true

And a record from the original reported dataset seems to be better: https://biocache-databox.ala.org.au/occurrences/62976ebf-3ef4-48ca-9302-564fda071a10

**Comment by peggynewman** [comment]
This is fixed in prod now. 
https://biocache.ala.org.au/occurrences/search?q=country%3AAustralia&fq=raw_eventDate%3A*&fq=-eventDate%3A*&qualityProfile=ALA&disableAllQualityFilters=true.
